FROM ubuntu:16.04

RUN echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable xenial main" > /etc/apt/sources.list.d/gazebo-stable.list && \
    apt-key adv --fetch-keys http://packages.osrfoundation.org/gazebo.key && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y apt-utils unzip wget gazebo7 libgazebo7-dev

RUN wget https://d3qzlqwby7grio.cloudfront.net/H520/sitl/Linux/Yuneec-SITL-Simulation-Linux.zip -P /tmp/ && \
    mkdir /yuneec && \
    unzip /tmp/Yuneec-SITL-Simulation-Linux.zip -d /yuneec/ && \
    ln -s /yuneec/posix-configs/SITL/init/default /yuneec/posix-configs/SITL/init/ekf2 && \
    rm  /tmp/Yuneec-SITL-Simulation-Linux.zip && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 14540
EXPOSE 14550

WORKDIR /root
CMD HEADLESS=1 /root/typhoon_sitl.bash
